from task_manager import TaskManager
from progress_tracker import ProgressTracker
from weekly_review import WeeklyReview
from daily_briefing import DailyBriefing
from daily_review import DailyReview
from outlook_module import OutlookEmail  # your Outlook email integration
from datetime import datetime

class OutlookEmailSummary:
    def __init__(self):
        self.tm = TaskManager()
        self.pt = ProgressTracker()
        self.dr = DailyReview()
        self.db = DailyBriefing()
        self.wr = WeeklyReview()
        self.outlook = OutlookEmail()

    # ---------------------------------------------------------
    # DAILY SUMMARY EMAIL
    # ---------------------------------------------------------
    def send_daily_summary(self):
        metrics = self.pt.calculate_progress()
        review = self.dr.generate_review()

        subject = f"Daily Summary — {datetime.now().strftime('%A, %B %d, %Y')}"
        body = f"""
Hello Felipe,

Here is your daily productivity summary generated by your Command Center:

============================================================
📊 **Daily Metrics**
- Completed Tasks: {metrics['completed_tasks']}
- Remaining Tasks: {metrics['incomplete_tasks']}
- Study Hours Logged: {metrics['total_completed_hours']}
- Backlog Hours Remaining: {metrics['total_remaining_hours']}
- Daily Velocity: {metrics['daily_velocity']}
- Momentum Score: {metrics['momentum']}
============================================================

{review}

Best,
Your Command Center
"""

        self.outlook.send_email(subject, body)
        return "Daily summary email sent."

    # ---------------------------------------------------------
    # WEEKLY SUMMARY EMAIL
    # ---------------------------------------------------------
    def send_weekly_summary(self):
        metrics = self.pt.calculate_progress()
        weekly = self.wr.generate_weekly_review()

        subject = f"Weekly Sprint Report — Week Ending {datetime.now().strftime('%B %d, %Y')}"
        body = f"""
Hello Felipe,

Here is your weekly sprint report:

============================================================
🏁 **Weekly Velocity:** {metrics['weekly_velocity']}
⏱ **Study Hours Logged:** {metrics['total_completed_hours']}
📚 **Remaining Backlog Hours:** {metrics['total_remaining_hours']}
🔥 **Momentum Score:** {metrics['momentum']}
============================================================

{weekly}

Best,
Your Command Center
"""

        self.outlook.send_email(subject, body)
        return "Weekly summary email sent."

    # ---------------------------------------------------------
    # OVERDUE TASK ALERT
    # ---------------------------------------------------------
    def send_overdue_alerts(self):
        tasks = self.tm.list_tasks()
        overdue = []

        for t in tasks:
            created = datetime.fromisoformat(t["created_at"])
            if (datetime.now() - created).days >= 3 and not t["completed"]:
                overdue.append(t)

        if not overdue:
            return "No overdue tasks."

        subject = "Overdue Task Alert"
        body = "Hello Felipe,\n\nThe following tasks are overdue:\n\n"

        for t in overdue:
            body += f"- {t['title']} (Category: {t['category']}, Estimate: {t['estimate']} hours)\n"

        body += "\nConsider scheduling these tasks soon.\n\nBest,\nYour Command Center"

        self.outlook.send_email(subject, body)
        return "Overdue task alert sent."

    # ---------------------------------------------------------
    # CONSISTENCY REMINDER
    # ---------------------------------------------------------
    def send_consistency_reminder(self):
        metrics = self.pt.calculate_progress()

        if metrics["daily_velocity"] == 0:
            subject = "Consistency Reminder"
            body = f"""
Hello Felipe,

You logged **0 completed tasks today**.

Momentum matters — consider scheduling a short study block tomorrow.

Best,
Your Command Center
"""
            self.outlook.send_email(subject, body)
            return "Consistency reminder sent."

        return "No consistency reminder needed."


if __name__ == "__main__":
    oes = OutlookEmailSummary()
    print(oes.send_daily_summary())
    print(oes.send_weekly_summary())
    print(oes.send_overdue_alerts())
    print(oes.send_consistency_reminder())
